name: code_collab_lints
description: A starting point for Dart libraries or applications.
repository: https://github.com/CodeCollabHub/code_collab_lints
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
